version: "2.4"
services:
  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    env_file:
      - .env
    ports:
      - "5001:5001"
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    env_file:
      - .env
    ports:
      - "5050:5050"
  ruby:
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
  csharp:
    build:
      context: .
      dockerfile: ./c-sharp/Dockerfile
    env_file:
      - .env
    ports:
      - "5080:80"
  go:
    build:
      context: .
      dockerfile: ./golang/Dockerfile
    env_file:
      - .env
    ports:
      - "5010:5010"

