services:
  python:
    build:
      context: .
      dockerfile: ./python/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
  node:
    build:
      context: .
      dockerfile: ./node/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"